# Test this without rebuilding the docker image $> docker-compose -f docker-compose-project2.yml up
# Test this with rebuilding the docker image $> docker-compose -f docker-compose-project2.yml up --build

version: '3.7'

services:
  peer1:
    build:
      context: .
      dockerfile: Dockerfile-project2
    image: project2:latest
    container_name: peer1
    working_dir: /csci251/project2
    volumes:
      - ./project2:/project2
    environment:
      - HOSTNAME=peer1
    networks:
      - csci251network
    ports:
      - 9091
      - 9092
    command:
      - /bin/bash
      - -c
      - |
        echo "Initialized peer1"
        tail -f /dev/null


  peer2:
    image: project2:latest
    container_name: peer2
    depends_on:
      - peer1
    working_dir: /csci251/project2
    volumes:
      - ./project2:/project2
    environment:
      - HOSTNAME=peer2
    networks:
      - csci251network
    ports:
      - 9091
      - 9092
    command:
      - /bin/bash
      - -c
      - |
        echo "Initialized peer2"
        tail -f /dev/null

  peer3:
    image: project2:latest
    container_name: peer3
    depends_on:
      - peer2
    working_dir: /csci251/project2
    volumes:
      - ./project2:/project2
    environment:
      - HOSTNAME=peer3
    networks:
      - csci251network
    ports:
      - 9091
      - 9092
    command:
      - /bin/bash
      - -c
      - |
        echo "Initialized peer3"
        tail -f /dev/null



networks:
  csci251network: